# site settings
title: Unity of Man
subtitle: Be Good * Do Good * Be One
email: youremailaddress@gmail.com
description: This target of this project is to provide the software support for the workflows in the Kirpal Sagar Charitable Hospital. It is currently in the inception stage.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
encoding: utf-8

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ksch-workflows
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
