# Site settings
baseurl = "/"
languageCode = "en-gb"
title = "KSCH Workflows"
theme = "syna"
enableGitInfo = true

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "KS Plus e.V."
  description = "IT system for the Kirpal Sagar Charitable Hospital"

  [params.style]
    #background = "secondary"
  [params.custom]
    favicon = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#C0C0C0"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/documentation"
  name = "Documentation"
  weight = 11

[[menu.main]]
  url = "/about"
  name = "About"
  weight = 20

[[menu.main]]
  url = "/contact"
  name = "Contact"
  weight = 30

[[menu.copyright_footer]]
  url = "imprint"
  name = "Imprint"
  weight = 30

[[menu.footer_social]]
  weight = 10
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/ksch-workflows"

[[menu.footer_social]]
  weight = 30
  name = "Mailing list"
  pre = "fas fa-mail-bulk"
  url = "https://groups.google.com/forum/#!forum/ksch-workflows"
